version: '3.3'

services:
   mysql_db:
     image: mysql:5.7
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - mysql_db
     image: bniesobski/wordpress-kyma
     ports:
       - "8000:80"
     environment:
       WORDPRESS_DB_HOST: mysql_db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
